### PR TITLE
create-hometown.md

### PR DESCRIPTION
**Pull request by Francine83**
made a file with attractions for the DMV area

### CODE REVIEW

**Comment by vmhunsley** [comment]
What a great place to go!  I think this should be included in the branch! 👍

**Comment by idrmiller** [comment]
What about the Casino next to Arundel Mills, any good?

**Comment by Francine83** [comment]
Not sure...... haven't been to the one in Arundel Mills

**Comment by Francine83** [comment]
Thank you VM

**Comment by vmhunsley** [comment]
Like the changes (casino is fun!)

**Pull request merged**
